# Generated by Django 4.1.7 on 2023-03-31 03:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ciry",
            new_name="city",
        ),
    ]
